[package]
name = "breakwater"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "3.2", features = ["derive"] }
rusttype = "0.9"
number_prefix = "0.4"
prometheus = "0.13"
prometheus_exporter = "0.8"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
vncserver = "0.2"

[dev-dependencies]
rstest = "0.12"
lazy_static = "1.4"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3

[features]
count_pixels = []
