[package]
name = "breakwater"
version = "0.0.1"
edition = "2018"

[dependencies]
clap = { version = "3.1.12", features = ["derive"] }
rusttype = "0.9.2"
number_prefix = "0.4.0"
prometheus = "0.13.0"
prometheus_exporter = "0.8.4"
serde_json = "1.0.80"
serde = { version = "1.0.137", features = ["derive"] }
vncserver = "0.2.2"

[dev-dependencies]
rstest = "0.12.0"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3

[features]
count_pixels = []
