version: '3'
services:
  pixelflut:
    restart: unless-stopped
    image: sbernauer/breakwater
    # build: .
    ports:
      - 1234:1234
      - 5900:5900
      - 9100:9100

  node-exporter:
    restart: unless-stopped
    image: prom/node-exporter:v1.8.0
    ports:
      - 9101:9101
    pid: host
    volumes:
      - "/:/host:ro,rslave"
    command:
      - "--path.rootfs=/host"
      - "--web.listen-address=:9101"

  prometheus:
    restart: unless-stopped
    image: prom/prometheus:v2.52.0
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus-data:/prometheus"
    ports:
      - 9090:9090

  grafana:
    restart: unless-stopped
    image: grafana/grafana:10.1.10
    volumes:
      - "./grafana/provisioning:/etc/grafana/provisioning/"
      - "grafana-data:/var/lib/grafana"
    ports:
      - 3000:3000

volumes:
  grafana-data:
  prometheus-data:
